# Generated by Django 5.0.6 on 2025-01-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Click",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("count", models.IntegerField(default=0)),
                ("session_key", models.CharField(max_length=255)),
            ],
        ),
    ]
